name: Inclass 3 Bruno Silva

on: push

jobs: 
  job-to-do-2-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: java App.java
